### ISSUE TITLE
Initial value doesn't remove on tap badge 

### ISSUE THREAD

**Issue by HekmatFavid** [CHB61/multi_select_flutter#127]
When using initialValue for MultiSelectBottomSheetField, tapping on initial selected badges doesn't work.
For example:
`                       
                         List<Object?> _selectedAnimals = [animal[2], animal[1]];

                         initialValue = _selectedAnimals;

                         onTap: (value) {
                          setState(() {
                              _selectedAnimals.remove(value);
                          });
`

**Comment by Bassiuz** [comment]
I experience the same issue. After submitting the initial values once, you can remove them with the chip selection. Before the first submit, changing the list in the state doesn't seem to trigger the rerender.

**Comment by Bassiuz** [comment]
I solved the issue in a fork; it had to do with the initialItems assignment. Instead of assigning the actual list, it created a new list and added the items. This way, the initial items don't have the same list as an assignment as the initialValues in your local state. So when the list in your local state gets edited, the list that is loaded in the chips isn't changed.

https://github.com/CHB61/multi_select_flutter/pull/130

**Comment by HekmatFavid** [comment]
Thank's a lot @Bassiuz. It solves problem. I hope your fork will merged to the main branch immediately.
