### ISSUE TITLE
Slow with big list

### ISSUE THREAD

**Issue by khamisEDX** [CHB61/multi_select_flutter#18]
Hi there I tried this plugin with nearly 600 item in the list it takes almost 10 seconds to open the dialog box and it's slow while scrolling. UI is perfect but I couldn't use it because it was slow

**Comment by CHB61** [comment]
Hello, thanks for bringing this up.

With 10,000 items it took nearly a minute to open the dialog!

Using a ListView.builder solves this. I'll be releasing this fix shortly.

Unfortunately I don't know of a great way to use ListView.builder if you wanted to use a chip style list that wraps. Currently it's a Wrap widget in a SingleChildScrollView.

Using a GridView is the closest I can get, but this changes the UI too much by putting list items in columns and rows. Ex.

<img src="https://i.imgur.com/2YyJJNY.png" alt="drawing" width="250"/>

So for now I'll be able to apply the fix for the regular checkbox-style list only and if you have a large list, you'll need to use that.

**Comment by CHB61** [comment]
@khamisEDX Fixed in v3.1.8 (except when using MultiSelectListType.CHIP)
